baseURL = "http://example.org/"
languageCode = "en-us"
title = "TED LZY Site"
theme = "m10c"
[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"



[[params.social]]
  name = "github"
  url = "https://github.com/Ted-L"

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"

